nome = input('Digite Seu nome completo: ')
print(nome)
print(nome.upper())
print(nome.lower())
nomese = nome.replace(' ', '')
print(len(nome))
print(len(nomese))
dividido = nome.split()
print(dividido[0])
